"""
Flask server for the LLM Agent.
Provides /chat (Ollama + conversation memory) and /tts (gTTS audio) endpoints.
"""

import io
import json
from datetime import datetime, timedelta

from flask import Flask, render_template, request, jsonify, send_file
from gtts import gTTS
import ollama

from config import OLLAMA_MODEL, SYSTEM_PROMPT
from intent_parser import extract_json, strip_json_block

app = Flask(__name__)

# ---------------------------------------------------------------------------
# In-memory conversation store  (session_id -> message list)
# For a prototype this is fine; production would use a DB or Redis.
# ---------------------------------------------------------------------------
conversations: dict[str, list[dict]] = {}


def _today_context() -> str:
    """Return a short string with today's date info for the system prompt."""
    now = datetime.now()
    tomorrow = now + timedelta(days=1)
    return (
        f"Today is {now.strftime('%A, %Y-%m-%d')}. "
        f"Tomorrow is {tomorrow.strftime('%A, %Y-%m-%d')}. "
        f"Current time is {now.strftime('%H:%M')}."
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    """Serve the chat UI."""
    return render_template("index.html")


@app.route("/chat", methods=["POST"])
def chat():
    """
    Accept a user message, forward it to Ollama with conversation history,
    and return the assistant's reply + any extracted intent JSON.
    """
    data = request.get_json(force=True)
    user_message = data.get("message", "").strip()
    session_id = data.get("session_id", "default")

    if not user_message:
        return jsonify({"error": "Empty message"}), 400

    # Initialise conversation if new session
    if session_id not in conversations:
        conversations[session_id] = []

    history = conversations[session_id]

    # Build the messages payload for Ollama
    system_msg = {
        "role": "system",
        "content": SYSTEM_PROMPT + "\n\n" + _today_context(),
    }
    messages = [system_msg] + history + [{"role": "user", "content": user_message}]

    # Call Ollama
    try:
        response = ollama.chat(model=OLLAMA_MODEL, messages=messages)
        assistant_reply = response["message"]["content"]
    except Exception as e:
        return jsonify({"error": f"Ollama error: {e}"}), 500

    # Save to history
    history.append({"role": "user", "content": user_message})
    history.append({"role": "assistant", "content": assistant_reply})

    # Try to extract intent JSON
    intent_json = extract_json(assistant_reply)
    display_text = strip_json_block(assistant_reply) if intent_json else assistant_reply

    return jsonify({
        "reply": display_text,
        "intent_json": intent_json,
    })


@app.route("/tts", methods=["POST"])
def tts():
    """
    Accept text and return MP3 audio generated by gTTS.
    """
    data = request.get_json(force=True)
    text = data.get("text", "").strip()

    if not text:
        return jsonify({"error": "Empty text"}), 400

    try:
        audio_io = io.BytesIO()
        gTTS(text=text, lang="en").write_to_fp(audio_io)
        audio_io.seek(0)
        return send_file(audio_io, mimetype="audio/mpeg")
    except Exception as e:
        return jsonify({"error": f"TTS error: {e}"}), 500


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print(f"🚀  LLM Agent starting — model: {OLLAMA_MODEL}")
    print(f"📅  {_today_context()}")
    print(f"🌐  Open http://localhost:5000 in Chrome for voice features")
    app.run(debug=True, host="0.0.0.0", port=5000)
